In [15]:
import pandas as pd
from pycaret.regression import *
import seaborn as sns

In [16]:
df = pd.read_csv('WALMART_SALES_DATA.csv')
print(df.dtypes)
df.head()

Store             int64
Date             object
Weekly_Sales    float64
Holiday_Flag      int64
Temperature     float64
Fuel_Price      float64
CPI             float64
Unemployment    float64
dtype: object

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [33]:
# obtendo métricas de desempenho da regressão linear
s = setup(df[['Store', 'Weekly_Sales']], target='Weekly_Sales',
          categorical_features=['Store'], session_id=0)
lr_model = create_model('lr')

In [34]:
# obtendo métricas de desempenho de vários modelos
s = setup(df[['Store', 'Weekly_Sales']], target='Weekly_Sales',
          categorical_features=['Store'], session_id=0)
model_only_store = compare_models()

In [126]:
# Testando modelos com todas as variáveis analisadas
s = setup(df, target = 'Weekly_Sales', ignore_features=['Date'], session_id=0)
best_model = compare_models(['lightgbm', 'rf', 'dt'])

In [129]:
# Avaliação dos modelos
print(best_model)
evaluate_model(best_model)

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=0, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…